<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TutorRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TutorRepository extends EntityRepository
{
    public function search($q, $limit = 10)
    {
        return $this->createQueryBuilder('tutor')
            ->where('CONCAT(tutor.firstName, \' \',tutor.lastName) LIKE :name')
            ->setParameter('name', '%' . $q . '%')
            ->setMaxResults($limit)
            ->getQuery()->getResult();
    }
}
