<?php

namespace TimetableBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FieldRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class FieldRepository extends EntityRepository
{
    public function search($q, $limit = 10)
    {
        return $this->createQueryBuilder('field')
            ->where('field.name LIKE :name')
            ->setParameter('name', '%' . $q . '%')
            ->setMaxResults($limit)
            ->getQuery()->getResult();
    }

    public function findAllQueryBuilder() {
        return $this->createQueryBuilder('field');
    }

    public function findListQueryBuilder() {
        $qb = $this->findAllQueryBuilder();
        $qb->join('field.tutor', 'tutor')->addSelect('tutor');
        $qb->join('field.organizationUnit', 'organization_unit')->addSelect('organization_unit');
        return $qb;;
    }

    public function findWithJoins($id) {
        $qb = $this->findAllQueryBuilder();
        $qb->join('field.tutor', 'tutor')->addSelect('tutor');
        $qb->join('field.organizationUnit', 'organizationUnit')->addSelect('organizationUnit');
        $qb->leftjoin('field.studentGroups', 'student_groups')->addSelect('student_groups');
        $qb->where('field.id = :id')->setParameter('id', $id);
        return $qb->getQuery()->getSingleResult();
    }
}
