<?php

namespace TimetableBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StudentGroupRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class StudentGroupRepository extends EntityRepository
{
    public function search($q, $limit = 10)
    {
        return $this->createQueryBuilder('student_group')
            ->where('student_group.name LIKE :name')
            ->setParameter('name', '%' . $q . '%')
            ->setMaxResults($limit)
            ->getQuery()->getResult();
    }

    public function findAllQueryBuilder() {
        return $this->createQueryBuilder('student_group');
    }

    public function findListQueryBuilder() {
        $qb = $this->findAllQueryBuilder();
        $qb->join('student_group.field', 'field')->addSelect('field');
        return $qb;;
    }

    public function findWithJoins($id) {
        $qb = $this->findAllQueryBuilder();
        $qb->leftjoin('student_group.events', 'event')->addSelect('event');
        $qb->innerJoin('event.tutor', 'tutor')->addSelect('tutor');
        $qb->innerJoin('event.subject', 'subject')->addSelect('subject');
        $qb->innerJoin('student_group.field', 'field')->addSelect('field');

        $qb->where('student_group.id = :id')->setParameter('id', $id);
        return $qb->getQuery()->getSingleResult();
    }
}
